name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Only run when pushing tags like v1.0.0

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Collate artefacts in folder
      - name: Build dist folder
        run: |
          cp src/Mother.cs /
          cp src/.gitignore /
          cp src/.gitattributes /

          cp -r src/Commands /
          cp -r src/Modules /
          cp -r src/Utilities /

          cp CHANGELOG.md /
          cp LICENSE.md /
          cp README.md /

      # 3. Create a zip archive
      - name: Archive dist
        run: zip -r mother-core.zip /

      # 4. Create GitHub Release from the tag
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: mother-core.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
