using SpaceEngineers.Game.ModAPI.Ingame;
using VRage.Game.ModAPI.Ingame;

namespace MotherCore.Tests.Utilities.Mocks
{
    /// <summary>
    /// Lightweight test fake for <see cref="IMyAirVent"/> used by module and command-path harness tests.
    /// </summary>
    /// <remarks>
    /// Citations:
    /// <see href="https://malforge.github.io/spaceengineers/pbapi/SpaceEngineers.Game.ModAPI.Ingame.IMyAirVent.html"/>
    /// <see href="https://malforge.github.io/spaceengineers/pbapi/SpaceEngineers.Game.ModAPI.Ingame.VentStatus.html"/>
    /// </remarks>
    internal sealed class FakeAirVent : FakeTerminalBlock, IMyAirVent
    {
        /// <summary>
        /// Initializes a fake air vent with optional identity and grid placement metadata.
        /// </summary>
        /// <param name="customName">Terminal display name for selector-based command tests.</param>
        /// <param name="customData">Custom data payload consumed by hook/config tests.</param>
        /// <param name="entityId">Optional explicit entity id; autogenerated when omitted by factory.</param>
        /// <param name="cubeGrid">Optional owning grid association.</param>
        public FakeAirVent(
            string customName = null,
            string customData = "",
            long? entityId = null,
            IMyCubeGrid cubeGrid = null)
            : base(customName, customData, entityId, cubeGrid)
        {
        }

        /// <summary>
        /// Gets or sets whether the vent is in depressurize mode.
        /// </summary>
        public bool Depressurize { get; set; }

        /// <summary>
        /// Gets whether the vent is currently depressurizing.
        /// Mirrors <see cref="Depressurize"/> for deterministic tests.
        /// </summary>
        public bool IsDepressurizing
        {
            get { return Depressurize; }
        }

        /// <summary>
        /// Gets or sets the current vent status for state-monitor transition tests.
        /// </summary>
        public VentStatus Status { get; set; } = VentStatus.Depressurized;

        /// <summary>
        /// Gets or sets whether the room can be pressurized (airtight state).
        /// </summary>
        public bool CanPressurize { get; set; } = true;

        /// <summary>
        /// Gets or sets whether pressurization is enabled.
        /// </summary>
        public bool PressurizationEnabled { get; set; } = true;

        /// <summary>
        /// Gets or sets a backing oxygen level used by <see cref="GetOxygenLevel"/>.
        /// </summary>
        public float OxygenLevel { get; set; }

        /// <summary>
        /// Returns the configured oxygen level.
        /// </summary>
        /// <returns>The current fake oxygen level.</returns>
        public float GetOxygenLevel()
        {
            return OxygenLevel;
        }

        /// <summary>
        /// Returns whether the vent is considered pressurized.
        /// </summary>
        /// <returns><see langword="true"/> when <see cref="CanPressurize"/> is set.</returns>
        public bool IsPressurized()
        {
            return CanPressurize;
        }
    }
}